apiVersion: v1
kind: Service
metadata:
  name: webapps-svc
  namespace: default
spec:
  selector:
    app: webapps
  type: NodePort
  ports:
  - name: webapps
    port: 
    targetPort: 
    protocol: TCP
    nodePort: 30080